apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-accounts-api
  labels:
    app: go-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-accounts
  template:
    metadata:
      labels:
        app: go-accounts
    spec:
      containers:
      - name: go-accounts-api
        image: 590184084151.dkr.ecr.ap-south-1.amazonaws.com/go-accounts:5a459eccbc9b643dd9caec32697bde7322ad362d
        ports:
        - containerPort: 3000
