apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::590184084151:user/go-accounts
      username: go-accounts
      groups:
        - system:masters