version: "3.8"

services:
  # Database
  postgres:
    image: postgres:12
    container_name: go-accounts-postgres
    volumes:
      - go-accounts-postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "${{ env.DB_PORT }}:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata

  # phppgadmin
  phppgadmin:
    image: dockage/phppgadmin
    container_name: go-accounts-phppgadmin
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgres
    depends_on:
      - postgres

  adminer:
    image: adminer
    container_name: go-accounts-adminer
    restart: always
    ports:
      - 8081:8080
    env_file:
      - .env
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  go-accounts-postgres-data:
    driver: local

networks:
  go-accounts-network:
    driver: bridge
    external: true
    name: go-accounts-network
