version: "3.8"

services:
  # Database
  postgres:
    image: postgres:12
    container_name: accounts-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - app.env
    environment:
      POSTGRES_USER: "accountUser"
      POSTGRES_PASSWORD: "accountPassword"
      POSTGRES_DB: "accounts"
      PGDATA: /var/lib/postgresql/data/pgdata

  # phppgadmin
  phppgadmin:
    image: dockage/phppgadmin
    container_name: accounts-phppgadmin
    restart: always
    ports:
      - "8080:80"
    env_file:
      - app.env
    environment:
      PHP_PG_ADMIN_SERVER_HOST: postgres
    depends_on:
      - postgres

  adminer:
    image: adminer
    container_name: accounts-adminer
    restart: always
    ports:
      - 8081:8080
    env_file:
      - app.env
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local

networks:
  accounts-network:
    driver: bridge
    external: true
    name: accounts-network
