// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: entry.sql

package db

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :execresult
INSERT INTO entries (account_id, amount, currency, exchange_rate) VALUES (?, ?, ?, ?)
`

type CreateEntryParams struct {
	AccountID    uint64  `json:"account_id"`
	Amount       float64 `json:"amount"`
	Currency     string  `json:"currency"`
	ExchangeRate float64 `json:"exchange_rate"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEntry,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.ExchangeRate,
	)
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries WHERE id = ?
`

func (q *Queries) DeleteEntry(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const getEntry = `-- name: GetEntry :one
SELECT account_id, amount, currency, exchange_rate, isdeleted, createdat, updatedat, id FROM entries WHERE id = ? LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id uint64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.AccountID,
		&i.Amount,
		&i.Currency,
		&i.ExchangeRate,
		&i.Isdeleted,
		&i.Createdat,
		&i.Updatedat,
		&i.ID,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT account_id, amount, currency, exchange_rate, isdeleted, createdat, updatedat, id FROM entries ORDER BY id LIMIT ?, ?
`

type ListEntriesParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.AccountID,
			&i.Amount,
			&i.Currency,
			&i.ExchangeRate,
			&i.Isdeleted,
			&i.Createdat,
			&i.Updatedat,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :execresult
UPDATE entries SET account_id = ?, amount = ?, currency = ?, exchange_rate = ? WHERE id = ?
`

type UpdateEntryParams struct {
	AccountID    uint64  `json:"account_id"`
	Amount       float64 `json:"amount"`
	Currency     string  `json:"currency"`
	ExchangeRate float64 `json:"exchange_rate"`
	ID           uint64  `json:"id"`
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEntry,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.ExchangeRate,
		arg.ID,
	)
}
