// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Account struct {
	Name      string    `json:"name"`
	Balance   float64   `json:"balance"`
	Currency  string    `json:"currency"`
	Isdeleted bool      `json:"isdeleted"`
	Createdat time.Time `json:"createdat"`
	Updatedat time.Time `json:"updatedat"`
	ID        uint64    `json:"id"`
}

type Entry struct {
	AccountID    uint64    `json:"account_id"`
	Amount       float64   `json:"amount"`
	Currency     string    `json:"currency"`
	ExchangeRate float64   `json:"exchange_rate"`
	Isdeleted    bool      `json:"isdeleted"`
	Createdat    time.Time `json:"createdat"`
	Updatedat    time.Time `json:"updatedat"`
	ID           uint64    `json:"id"`
}

type Transfer struct {
	SenderAccountID   uint64    `json:"sender_account_id"`
	ReceiverAccountID uint64    `json:"receiver_account_id"`
	Amount            float64   `json:"amount"`
	Currency          string    `json:"currency"`
	ExchangeRate      float64   `json:"exchange_rate"`
	Status            string    `json:"status"`
	Createdat         time.Time `json:"createdat"`
	Updatedat         time.Time `json:"updatedat"`
	ID                uint64    `json:"id"`
}
