// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Account struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Balance   string    `json:"balance"`
	Currency  string    `json:"currency"`
	IsDeleted bool      `json:"isDeleted"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Entry struct {
	ID           int64     `json:"id"`
	AccountID    int64     `json:"account_id"`
	Amount       string    `json:"amount"`
	Currency     string    `json:"currency"`
	ExchangeRate int32     `json:"exchange_rate"`
	IsDeleted    bool      `json:"isDeleted"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type Transfer struct {
	ID                int64     `json:"id"`
	SenderAccountID   int64     `json:"sender_account_id"`
	ReceiverAccountID int64     `json:"receiver_account_id"`
	Amount            string    `json:"amount"`
	Currency          string    `json:"currency"`
	ExchangeRate      float64   `json:"exchange_rate"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}
